name: My first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
  build-app-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
